---

- name: generate random secret
  shell: |
    set -o pipefail
    openssl rand -base64 32 | sed 's@[=\\/\\+]@@g;' | tee /root/.zentral_secret
  args:
    creates: "/root/.zentral_secret"
    executable: /bin/bash
  register: rand
  changed_when: false
  no_log: "{{ zentral_no_log | default(true) }}"
